-- Create public user
CREATE TABLE PUBLICUSER (USER_ID INTEGER NOT NULL, ADDRESS VARCHAR(255), EMAIL VARCHAR(255), FIRSTNAME VARCHAR(255), ISACTIVE SMALLINT DEFAULT 0 , LASTNAME VARCHAR(255), PASSWORD VARCHAR(255), PHONE VARCHAR(255), USER_TYPE VARCHAR(255), PRIMARY KEY (USER_ID));

-- Create public 
CREATE TABLE WORKER (USER_ID INTEGER NOT NULL, ADDRESS VARCHAR(255), EMAIL VARCHAR(255), FIRSTNAME VARCHAR(255), ISACTIVE SMALLINT DEFAULT 0 , LASTNAME VARCHAR(255), PASSWORD VARCHAR(255), PHONE VARCHAR(255), USER_TYPE VARCHAR(255), PRIMARY KEY (USER_ID));

-- Create Service
CREATE TABLE SERVICE (SERVICE_NO INTEGER NOT NULL, DESCRIPTION VARCHAR(255), ISACTIVE SMALLINT DEFAULT 0 , "NAME" VARCHAR(255), THUMBNAIL VARCHAR(255), "TYPE" VARCHAR(255), PRIMARY KEY (SERVICE_NO));

-- Create ServiceType
CREATE TABLE SERVICETYPE (TYPE_ID INTEGER NOT NULL, TYPE_NAME VARCHAR(255), PRIMARY KEY (TYPE_ID));

-- Create ServiceUse
CREATE TABLE SERVICEUSE (USEID INTEGER NOT NULL, IS_FINISHED SMALLINT DEFAULT 0 , USEDATE VARCHAR(255), MANAGED_BY INTEGER NOT NULL, USEDSERVICE INTEGER NOT NULL, USED_BY INTEGER NOT NULL, PRIMARY KEY (USEID));


-- CREATE SYSTEM USER VIEW FOR JAAS
CREATE VIEW SYSTEMUSERS AS
SELECT * 
FROM publicuser 
union all 
select * from worker;

---- Get assigned worker
SELECT COUNT(wo.USER_ID),wo.USER_ID,wo.LASTNAME from worker wo
left join ServiceUse w   on wo.USER_ID = w.MANAGED_BY 
GROUP BY wo.USER_ID,wo.LASTNAME ORDER BY COUNT(wo.USER_ID) asc;